### ISSUE TITLE
Support for Linux (Ubuntu)

### ISSUE THREAD

**Issue by AlexVinet** [Nerixyz/current-song2#363]
Hello, 
Would it be possible to have it on Ubuntu?

Thanks

**Comment by Nerixyz** [comment]
From briefly looking at Spotify's dbus interface, this seems to be possible. I'll add a CI job that builds on Ubuntu and later (hopefully) a Spotify integration. There are some other things to do as well.

### TODO

- [ ] Add Ubuntu CI
- [ ] Add `.deb` artifact
- [ ] Figure out a _good_ way of running in the background (probably through a systemd service)
- [ ] Add additional config locations
- [ ] Add Spotify dbus interface

**Comment by girlmaya** [comment]
How is the linux support now?

**Comment by Nerixyz** [comment]
If you have an executable (or through `cargo`), you can run the app and it should anything you're playing ([docs](https://currentsong.nerixyz.de/Building/)). I've tested it with Spotify on WSL. However, I don't know to deploy/package the app well and which "standards" I should adhere to. The config itself should be correctly stored ([docs](https://currentsong.nerixyz.de/Configuration/#unix)).
